// <auto-generated />
namespace SMUGBase.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AccessToken : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AccessToken));
        
        string IMigrationMetadata.Id
        {
            get { return "201307191114511_AccessToken"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
