// <auto-generated />
namespace SMUGBase.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class remandadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remandadd));
        
        string IMigrationMetadata.Id
        {
            get { return "201307041401047_remandadd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
