// <auto-generated />
namespace SMUGBase.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addlogged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addlogged));
        
        string IMigrationMetadata.Id
        {
            get { return "201307041155426_addlogged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
