// <auto-generated />
namespace SMUGBase.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addsecret : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addsecret));
        
        string IMigrationMetadata.Id
        {
            get { return "201307041407529_addsecret"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
